/* empty css                      */import{S as p,A as m}from"./assets/vendor-16iyBIrI.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();new p(".my-swiper",{modules:[m],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1.25,spaceBetween:16,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1},breakpoints:{1440:{slidesPerView:2,spaceBetween:24}}});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),i=r.querySelector(".icon"),a=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M34 30L10 30" stroke="white" stroke-width="2" stroke-linecap="round" />
  <path d="M34 22L10 22" stroke="white" stroke-width="2" stroke-linecap="round" />
  <path d="M34 14L10 14" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="44" height="44" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M20 20L4 4M20 4L4 20" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,i.innerHTML=t?o:l,t?n():s()}),d.forEach(u=>u.addEventListener("click",()=>{s(),i.innerHTML=l,t=!1})),window.addEventListener("scroll",c);function n(){a.style.display="block"}function s(){a.style.display="none"}function c(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function i(o){const n=document.getElementById(o);if(!n)return;const s=r(),c=n.getBoundingClientRect().top+window.pageYOffset-s;window.scrollTo({top:c,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const s=this.getAttribute("href");if(!s)return;const[c,u]=s.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(c===""||c==="./"||c===f||c==="./"+f)||!document.getElementById(u)||(n.preventDefault(),i(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(s=>s.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function l(){const o=window.pageYOffset+r()+100;d.forEach(n=>{const s=n.offsetTop,c=s+n.offsetHeight;o>=s&&o<c&&t(n.id)})}if(window.addEventListener("scroll",l),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{i(o),t(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("cookie-popup"),i=document.getElementById("accept-cookies"),a=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(r.style.display="block"),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),r.style.display="none"}),a.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),r.style.display="none"})});
//# sourceMappingURL=index.js.map
